\import LogicUtil
\import Paths.Meta
\import Set
\import identity.DecMaps
\import identity.Identity

\instance SigmaIdentity {A B : Identity.Decidable} : Identity.Decidable (\Sigma A B)
  | Code x y => \Sigma (Code x.1 y.1) (Code x.2 y.2)
  | code-refl a => (code-refl a.1, code-refl a.2)
  | code-decode c => ext (code-decode c.1, code-decode c.2)
  | code-decide a b => decMap2 (Identity.code-decide a.1 b.1) (Identity.code-decide a.2 b.2) <->.refl <->.refl

