\import lambda.GeneralContext

{-
- Intrinsicly types lambda calculus with base types
- -}

\data Type
  | Base (B : \Set)
  | \infixr 6 --> (A B : Type)

\func SimpleContext => Context Type
\func SimpleLookup => (∋) {Type}

\data Term \alias \infix 5 ⊢ (c : SimpleContext) (T : Type)
  \elim T
  | Base B => base B
  | T => var (c ∋ T)
  | --> A B => lam (c ∕ A ⊢ B)
  | B => app \alias \infixl 6 ⋅ {A : Type} (c ⊢ A --> B) (c ⊢ A)

\func example {A : Type} : ∅ ⊢ A --> A => lam (var #0)